name: StudManager CI/CD

on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      working-directory: .\StudManager
    - name: Make Directory for test results
      run: mkdir -p testresults
    - name: Test
      run: dotnet test  --logger html --results-directory testresults --no-build
    - name: Upload test results
      run: actions/upload-artifact@v2
      with:
        name: TestRunReports
        path: testresults